Add code of conduct
sous-chefs/meta pull request #29
Opened 2015-07-20 00:41 UTC by dblessing

Added a standard code of conduct adapted from http://contributor-covenant.org/version/1/1/0/

2015-07-20 13:12 UTC, martinb3 commented
Maybe we could cite the Chef Community guidelines as well?

2015-07-20 13:34 UTC, dblessing commented
As long as they don't conflict. Maybe it would be better to copy theirs so they are in agreement?

2015-07-20 18:29 UTC, zuazo commented
Chef Community Guidelines here: https://docs.chef.io/community_guidelines.html

Your proposal sounds good anyway. Short and clear :+1:

2016-12-08 22:06 UTC, damacus approved these changes

2016-12-08 22:09 UTC, zuazo approved these changes

2016-12-09 03:27 UTC, shortdudey123 requested changes

2016-12-09 03:27 UTC, shortdudey123 commented on CODE_OF_CONDUCT.md
> +# Chef Brigade Contributor Code of Conduct
Name change

2016-12-09 03:27 UTC, shortdudey123 commented on CODE_OF_CONDUCT.md
> +As contributors and maintainers of projects within Chef Brigade, we pledge to respect all people
Here too

2016-12-09 17:41 UTC, damacus commented
@shortdudey123 That should fix those issues.

2016-12-09 18:25 UTC, shortdudey123 approved these changes

2016-12-09 18:46 UTC, josephholsten commented
We voted to used a modified version of the chef code of conduct, so this is no longer correct.

2016-12-09 18:46 UTC, closed without merging