Rename the org
sous-chefs/meta pull request #38
Opened 2016-11-30 15:25 UTC by damacus

2016-11-30 15:35 UTC, josephholsten approved these changes

2016-11-30 17:49 UTC, shortdudey123 approved these changes

2016-11-30 18:20 UTC, zuazo requested changes

2016-11-30 18:20 UTC, zuazo commented on README.md
>  Home for discussion about Chef Brigade, and various guides for cookbook authors.
You can also change the *Chef Brigade* string here.

2016-11-30 18:30 UTC, svanzoest approved these changes

2016-12-01 13:27 UTC, webframp commented
Guessing also a rename here would be needed: https://supermarket.chef.io/users/chef-brigade ?

2016-12-01 13:39 UTC, damacus commented
@webframp yeah we probably want to rename that too. 

I've been a bit more comprehensive this time.

2016-12-01 13:41 UTC, zuazo approved these changes

2016-12-01 13:42 UTC, merged