Provide example documentation for forking an existing repo (super basic)
sous-chefs/meta pull request #40
Opened 2016-12-08 22:04 UTC by damacus

Remove -cookbook suffix as per discussion in issue #3
fix another brigade

https://github.com/sous-chefs/meta/issues/3

2016-12-08 22:21 UTC, zuazo approved these changes

2016-12-08 22:33 UTC, tas50 requested changes

2016-12-08 22:33 UTC, tas50 commented on transfering-a-cookbook.md
>  maintainer_email 'help@chefsous-chefs.io'
help@sous-chefs.org

2016-12-09 00:40 UTC, tas50 approved these changes
Lets merge it

2016-12-09 00:43 UTC, merged

2016-12-09 20:43 UTC, damacus commented on transfering-a-cookbook.md
>  maintainer_email 'help@chefsous-chefs.io'
@tas50 this should now be fixed 👍