Adds labels
sous-chefs/meta pull request #44
Opened 2016-12-09 19:53 UTC by damacus

https://github.com/sous-chefs/meta/issues/41

2016-12-09 19:53 UTC, damacus commented
The colours are wrong for the last set. Feel free to amend.

2016-12-09 19:56 UTC, shortdudey123 requested changes
Since most of the labels are capitalized with no `_`, the last couple labels in the list should probably be fixed

2016-12-09 19:57 UTC, shortdudey123 commented on config/github_labels.json
> +  { "name": "Type: feedback_requested","color": "cc317c" }
This one actually is not needed since we have `Pending Contributor Response`

2016-12-09 22:12 UTC, shortdudey123 approved these changes

2016-12-09 22:15 UTC, tas50 commented on config/github_labels.json
> +  { "name": "Type: Failing Test", "color": "cc317c" },
This is probably a status, but I'm not sure if we need it since you also have a big red X showing you the tests are failing and if the user updates the tests this label doesn't magically go away

2016-12-09 22:16 UTC, tas50 commented on config/github_labels.json
> +  { "name": "Type: Easy", "color": "cc317c" },
This should probably be Easy Fix

2016-12-09 22:16 UTC, shortdudey123 commented on config/github_labels.json
> +  { "name": "Type: Failing Test", "color": "cc317c" },
Tend to agree here

2016-12-09 23:16 UTC, tas50 commented
Colors are wrong for a lot of them. It's surprisingly hard to find a solid list of unique colors.

2016-12-10 12:29 UTC, zuazo commented
I propose to use [Kelly's 22 color list from here](http://stackoverflow.com/questions/470690/how-to-automatically-generate-n-distinct-colors/4382138#4382138).

For example, based on your colors:

```js
[
  { "name": "Status: Abandoned", "color": "232c16" },
  { "name": "Status: Blocked", "color": "593315" },
  { "name": "Status: In Progress", "color": "817066" },
  { "name": "Status: On Hold", "color": "cea262" },
  { "name": "Status: Maintainer Review Needed", "color": "ff8e00" },
  { "name": "Status: Pending Contributor Response", "color": "f6768e" },
  { "name": "Priority: Low", "color": "4d0000" },
  { "name": "Priority: Medium", "color": "800000" },
  { "name": "Priority: High", "color": "b30000" },
  { "name": "Priority: Critical", "color": "ff0000" },
  { "name": "Type: Bug", "color": "f13a13" },
  { "name": "Type: Maintenance", "color": "f4c800" },
  { "name": "Type: Enhancement", "color": "a6bdd7" },
  { "name": "Type: Question", "color": "00538a" },
  { "name": "Type: Feature Request", "color": "007d34" },
  { "name": "Type: Help Wanted", "color": "53377a" },
  { "name": "Type: Easy Fix", "color": "93aa00" },
  { "name": "Type: Feedback Requested","color": "b32851" }
]
```

![github_labels](https://cloud.githubusercontent.com/assets/1878434/21073322/1730374a-bedb-11e6-9b48-a2bc8d7aa52a.png)

Online code example [here](https://jsfiddle.net/2qetwquz/).

More colors to use from that list:

- ffb300 (Vivid Yellow)
- 803e75 (Strong Purple)
- ff6800 (Vivid Orange)
- c10020 (Vivid Red)
- ff7a5c (Strong Yellowish Pink)
- 7f180d (Strong Reddish brown)

2016-12-10 13:54 UTC, zuazo approved these changes

2016-12-10 23:50 UTC, svanzoest approved these changes

2016-12-16 20:10 UTC, merged