Add repo setup
sous-chefs/meta pull request #53
Opened 2017-01-20 17:19 UTC by damacus

2017-01-20 18:33 UTC, rshade approved these changes

2017-01-20 19:00 UTC, tas50 commented on repository-setup.md
> +- Master is always Protected.
We should elaborate here since there's several options for protected master.

2017-01-20 21:03 UTC, rshade commented on repository-setup.md
> +- Master is always Protected.
I guess maybe a screenshot of haproxy?

2017-01-27 17:53 UTC, josephholsten approved these changes
I'm comfortable with this as-is, but if you want to address the comments that would be even better!

2017-01-27 17:53 UTC, josephholsten commented on repository-setup.md
> +- Squash merging is up to the repository admin
s/admin/primary maintainer/ ?

2017-01-27 17:53 UTC, josephholsten commented on repository-setup.md
> +- Master is always Protected.
https://cl.ly/3u043G0x363M

2017-01-27 18:58 UTC, josephholsten approved these changes
LGTM

2017-01-27 19:00 UTC, tas50 commented on repository-setup.md
> +We aim to have clean understandable updates, and good git history. Rather than hiding a mess under the carpet.
Make this a 2nd sentence on the last item in the list. It's a supporting note for that specific item and not all the items

2017-01-27 19:01 UTC, tas50 commented on repository-setup.md
> +- Master is always Protected.
Protected probably doesn't need to be capitalized

2017-01-27 19:02 UTC, tas50 commented on repository-setup.md
> +- Squash merging is up to the repository primary maintainer
Merge strategy (squash vs. merge vs. rebase) is up to the repository's primary maintainer

2017-01-27 19:15 UTC, tas50 commented on repository-setup.md
> +# Example
Missing space is breaking the formatting

2017-01-27 19:15 UTC, tas50 approved these changes

2017-01-27 19:17 UTC, zuazo requested changes

2017-01-27 19:17 UTC, zuazo commented on repository-setup.md
> +  * We aim to have clean understandable updates, and good git history. Rather than hiding a mess under the carpet.
I think you need to add an empty line here. If you see the [View](https://github.com/sous-chefs/meta/blob/71e30a9968fca7eb89a59fb67420babea6bf7683/repository-setup.md), the `# Example` heading is not interpreted correctly.

2017-01-27 19:18 UTC, zuazo approved these changes

2017-01-27 19:19 UTC, merged