docs/contributing: add
sous-chefs/meta pull request #65
Opened 2017-02-28 02:08 UTC by josephholsten

2017-02-28 02:25 UTC, shortdudey123 commented on docs/CONTRIBUTING.md
> +[Test Kitchen](http://kitchen.ci/). It uses serverspec to run
some might use `inspec`

2017-02-28 02:28 UTC, shortdudey123 commented on docs/CONTRIBUTING.md
> +rules. FC007 is okay as long as the dependent cookbooks are *required*
Can you elaborate on `FC007`? maybe adding a specific example would help

2017-02-28 02:55 UTC, tas50 approved these changes

2017-02-28 02:55 UTC, tas50 commented on docs/CONTRIBUTING.md
> +[Test Kitchen](http://kitchen.ci/). It uses serverspec to run
That

2017-02-28 10:21 UTC, damacus requested changes
serverspec --> inspec.
Elaborate on FC007

2017-05-17 13:43 UTC, damacus commented
If this needs to be added still please add it to github.com/sous-chefs/sous-chefs/

2017-05-17 13:43 UTC, closed without merging