Add minutes!
sous-chefs/meta pull request #70
Opened 2017-05-09 09:00 UTC by damacus

2017-05-09 16:44 UTC, shortdudey123 commented on minutes/2017-05-08.md
> +- redisio: should be making a release in the next day or too which a _LARGE_ amount of updates sc-mongodb
wrong cookbook at the end :) 
that might be my bad in the google doc though

2017-05-09 16:44 UTC, shortdudey123 commented on minutes/2017-05-08.md
> +- Postgresql: still working on cluster testing in test-kitchen
`sc-mongodb`

2017-05-09 16:44 UTC, shortdudey123 commented on minutes/2017-05-08.md
> +- HAProxy: review of OS specific issues in progress HAProxy
`haproxy`

2017-05-09 16:45 UTC, shortdudey123 requested changes
several cookbook names got mixed up

2017-05-10 16:45 UTC, rshade commented
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sous-chefs/meta/70)*
<!-- Sent from Reviewable.io -->

2017-05-12 14:03 UTC, merged